name: Run R script every hour

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures à XX:00 UTC
  workflow_dispatch:      # Permet aussi de lancer manuellement le workflow

jobs:
  run-r-script:
    runs-on: ubuntu-latest  # Utilisation d'un runner GitHub pour le job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # Installer R et ses outils dans le container

      # Etape de mise en cache des packages R
      - name: Cache R library
        id: cache-r
        uses: actions/cache@v3
        with:
          path: ~/.local/share/R/library  # Emplacement des bibliothèques R installées
          key: ${{ runner.os }}-r-packages-${{ hashFiles('**/*.R') }}  # Clé de cache basée sur les fichiers .R
          restore-keys: |
            ${{ runner.os }}-r-packages-

      # Etape d'installation des packages R, seulement si nécessaire (si pas dans le cache)
      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("dplyr", "ggplot2", "tidyr", "lubridate"), repos="https://cloud.r-project.org")'  # Remplacer avec tes packages

      - name: Run R script
        run: |
          script/data-dl-and-prep.R