name: Run R script every hour

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures à XX:00 UTC
  workflow_dispatch:      # Permet aussi de lancer manuellement le workflow

jobs:
  run-r-script:
    runs-on: ubuntu-22.04  # Utilisation d'un runner GitHub pour le job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # Installer R et ses outils dans le container
        with:
          r-version: '4.4.3'  # specify the R version you want

      # Etape de mise en cache des packages R
      - name: Cache R library
        id: cache-r
        uses: actions/cache@v3
        with:
          path: ~/.local/share/R/library  # Emplacement des bibliothèques R installées
          key: ${{ runner.os }}-r-packages-${{ hashFiles('**/*.R') }}  # Clé de cache basée sur les fichiers .R
          restore-keys: |
            ${{ runner.os }}-r-packages-

      # Etape d'installation des packages R, seulement si nécessaire (si pas dans le cache)
      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("curl", "TTR", "magrittr", "dplyr", "tidyr", "lubridate", "quantmod", "readr", "purrr"), repos="https://cloud.r-project.org")'  # Remplacer avec tes packages

      - name: Run R script
        run: |
          Rscript script/data-dl-and-prep.R
          
      - name: Add data/tidy_markets_data_to_flourish.csv to git, commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/tidy_markets_data_to_flourish.csv
          git commit -m "Add generated data/tidy_markets_data_to_flourish.csv"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          